name: Deploy DilSeDaan to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: '8'
        
    - name: Install root dependencies
      run: pnpm install --no-frozen-lockfile
        
    - name: Install frontend dependencies
      run: |
        cd apps/frontend
        pnpm install --no-frozen-lockfile
        
    - name: Create environment file
      run: |
        cd apps/frontend
        echo "VITE_API_URL=https://api.dilsedaan.com/api" > .env
        echo "VITE_BACKEND_URL=https://api.dilsedaan.com" >> .env
        echo "VITE_APP_NAME=DilSeDaan" >> .env
        echo "VITE_APP_DESCRIPTION=India's Blockchain-Powered Charity Platform" >> .env
        echo "VITE_WEB3_PROVIDER_URL=https://polygon-mainnet.infura.io/v3/demo" >> .env
        echo "VITE_CONTRACT_ADDRESS=0x1234567890123456789012345678901234567890" >> .env
        echo "VITE_CHAIN_ID=137" >> .env
        echo "VITE_IPFS_GATEWAY_URL=https://ipfs.io/ipfs/" >> .env
        echo "VITE_TWITTER_HANDLE=@DilSeDaan" >> .env
        echo "VITE_FACEBOOK_PAGE=DilSeDaanIndia" >> .env
        echo "VITE_ENABLE_BLOCKCHAIN=true" >> .env
        echo "VITE_ENABLE_PUSH_NOTIFICATIONS=true" >> .env
        echo "VITE_ENABLE_PWA=true" >> .env
        
    - name: Build frontend
      run: |
        cd apps/frontend
        echo "Building frontend..."
        pnpm run build
        echo "Build completed successfully!"
        echo "Checking dist folder..."
        ls -la dist/
        echo "Checking images exist..."
        ls -la dist/images/ | head -5
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./apps/frontend/dist
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
